spring.application.name=levelup

spring.datasource.url=jdbc:postgresql://localhost:5432/levelup
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.open-in-view=false

jwt.secret=33badecd1280ae5f7a30ab31e8df63d680188efeb921dcf56bcd16fff2e9f051
jwt.expiration=86400000
# 24 hours